<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.0 (Python 3.9.2 on win32)" generated="20210414 15:52:52.094" rpa="false" schemaversion="2">
<suite id="s1" name="TEST" source="C:\Users\Laptop\PycharmProjects\RobotAutomation\TestCases\LoginTC\TEST.robot">
<test id="s1-t1" name="Fetch data2">
<kw name="Twee user en pass" library="Rescources1">
<arg>Steven</arg>
<arg>hzslf</arg>
<kw name="Con Two Val" library="Keywords">
<var>${result}</var>
<arg>${Username}</arg>
<arg>${password}</arg>
<msg timestamp="20210414 15:52:52.517" level="INFO">${result} = Stevenhzslf</msg>
<status status="PASS" starttime="20210414 15:52:52.517" endtime="20210414 15:52:52.518"/>
</kw>
<kw name="Log" library="BuiltIn">
<arg>${result}</arg>
<doc>Logs the given message with the given level.</doc>
<msg timestamp="20210414 15:52:52.519" level="INFO">Stevenhzslf</msg>
<status status="PASS" starttime="20210414 15:52:52.518" endtime="20210414 15:52:52.519"/>
</kw>
<status status="PASS" starttime="20210414 15:52:52.516" endtime="20210414 15:52:52.519"/>
</kw>
<status status="PASS" starttime="20210414 15:52:52.515" endtime="20210414 15:52:52.519"/>
</test>
<status status="PASS" starttime="20210414 15:52:52.098" endtime="20210414 15:52:52.521"/>
</suite>
<statistics>
<total>
<stat pass="1" fail="0" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="1" fail="0" skip="0" id="s1" name="TEST">TEST</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210414 15:52:52.499" level="ERROR">Error in file 'C:\Users\Laptop\PycharmProjects\RobotAutomation\Rescources\Rescources1.robot' on line 3: Test library 'C:UsersLaptopPycharmProjectsRobotAutomationKeywords1.py' does not exist.</msg>
<msg timestamp="20210414 15:52:52.504" level="ERROR">Error in file 'C:\Users\Laptop\PycharmProjects\RobotAutomation\Rescources\Rescources1.robot' on line 4: Importing library 'Selenium' failed: ModuleNotFoundError: No module named 'Selenium'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\Laptop\AppData\Local\Programs\Python\Python39\Scripts\robot.exe
  c:\users\laptop\appdata\local\programs\python\python39\python39.zip
  c:\users\laptop\appdata\local\programs\python\python39\DLLs
  c:\users\laptop\appdata\local\programs\python\python39\lib
  c:\users\laptop\appdata\local\programs\python\python39
  c:\users\laptop\appdata\local\programs\python\python39\lib\site-packages</msg>
</errors>
</robot>
